#!/usr/bin/env python
"""
This script interacts with the Seqera Platform CLI to extract workflow metadata in a JSON file.
It is designed to be run from the command line, accepting parameters to specify
the workspace, workflow ID, and output path for the resulting JSON.

The script relies on the seqerakit package to interact with the CLI using Python and must
be run in an environment where this package is installed and properly configured. To install,
run `pip install seqerakit` in your environment.

Usage:
    python extract_metadata.py -w <workspace_name> -id <workflow_id> -o <output_file.json>

Arguments:
    -w, --workspace     The name of the workspace on the Seqera Platform.
    -id, --workflow_id  The unique identifier for the workflow.
    -o, --output        The path to the output JSON file that will be created with workflow information.

Example:
    python extract_metadata.py -w myworkspace -id 12345 -o workflow_details.json

Note: Ensure that the `TOWER_ACCESS_TOKEN` has been set in your environment before running the script.
"""

from seqerakit import seqeraplatform
import argparse
import json
import logging
import tarfile

from argparse import Namespace
from pathlib import Path
from tabulate import tabulate
from typing import Any, Dict, List


def parse_args() -> Namespace:
    """
    Parse command-line arguments.

    Returns:
        Namespace: An argparse.Namespace object containing the arguments 'output',
        'workspace', and 'workflow_id'.
    """
    parser = argparse.ArgumentParser(
        description="Extract and process Seqera Platform workflow metadata."
    )
    parser.add_argument(
        "-l",
        "--log_level",
        default="INFO",
        choices=("CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"),
        help="The desired log level (default: INFO).",
        type=str.upper,
    )
    parser.add_argument(
        "-o", "--output", type=str, required=True, help="Output filename for JSON file"
    )
    parser.add_argument(
        "-w",
        "--workspace",
        type=str,
        required=True,
        help="Seqera Platform workspace name",
    )
    parser.add_argument(
        "-id",
        "--workflow_id",
        type=str,
        required=True,
        nargs="+",
        help="Seqera Platform workflow ID",
    )
    return parser.parse_args()


def get_runs_dump(
    seqera: seqeraplatform.SeqeraPlatform, workflow_id: str, workspace: str
) -> str:
    """
    Run the `tw runs dump` command for a given workflow ID within a workspace and download archive as a tar.gz file.

    Args:
        seqera (SeqeraPlatform): An instance of the SeqeraPlatform class that interacts with the Seqera Platform CLI.
        workflow_id (str): The ID of the workflow to retrieve run data for.
        workspace (str): The name of the workspace in which the workflow was run.

    Returns:
        str: The name of the downloaded tar.gz file.
    """
    output_file = f"{workflow_id}.tar.gz"
    seqera.runs("dump", "-id", workflow_id, "-o", output_file, "-w", workspace)
    return output_file


def extract_workflow_data(tar_file: str) -> Dict[str, Any]:
    """
    Extract specified files from the tar archive generated by `tw runs dump` and load their contents as JSON.

    Args:
        tar_file (str): The path to the tar.gz file from `tw runs dump` to extract.
    Returns:
        dict: A dictionary where keys are the file names without extension and values are the text. If JSON it will be a dict, if any other it will be a string.
    """
    with tarfile.open(tar_file, "r:gz") as tar:
        extracted_data = {}
        for member in tar.getmembers():
            filename = Path(member.name).stem
            try:
                extracted_data[filename] = json.load(tar.extractfile(member))
            except json.JSONDecodeError:
                # Read in text as plain text for saving logs into list
                extracted_data[filename] = (
                    tar.extractfile(member).read().decode().split("\n")
                )
        return extracted_data


def parse_json(json_data: Dict[str, Any], keys: Dict[str, str]) -> Dict[str, Any]:
    """
    Parse a JSON object and return the values for the specified keys, including nested keys.

    Args:
        json_data (dict): The JSON input data to parse.
        keys_list (dict): A key value pair to extract from nested JSON. The key will be used for
            assignment in the output dictionary and the value will be what is extracted from the
            input JSON. Nested keys should be denoted with a period.

    Returns:
        dict: A dictionary of extracted key-value pairs from the JSON data.
    """
    update_dict = {}
    for key, val in keys.items():
        try:
            value = json_data
            for part in val.split("."):
                value = value.get(part)
                if value is None:
                    break
            else:
                update_dict[key] = value
        except (KeyError, TypeError):
            update_dict[key] = None
    return update_dict


def main() -> None:
    args = parse_args()
    logging.basicConfig(level=args.log_level)

    seqera = seqeraplatform.SeqeraPlatform()

    logging.info("Getting workflow run data...")
    tar_files = [
        get_runs_dump(seqera, workflowId, args.workspace)
        for workflowId in args.workflow_id
    ]

    logging.info("Extracting workflow metadata...")
    extracted_data = [extract_workflow_data(tar_file) for tar_file in tar_files]

    logging.info("Writing workflow metadata to JSON file...")
    with open(args.output, "w") as outfile:
        json.dump(extracted_data, outfile, indent=4)

    logging.info(f"Workflow metadata written to {args.output}.")

    # for x in extracted_data:
    #     # Need to add https://github.com/seqeralabs/tower-cli/pull/364 to get all information
    #     print(x["workflow-info"]["general"]["pipeline"])
    #     print(x["workflow-info"]["general"]["workspace"])
    #     print(x["workflow-info"]["general"]["url"])
    #     print(x["workflow-launch"]["computeEnv"]["name"])
    #     print(x["workflow"]["status"])
    #     print(x["service-info"]["version"])
    #     print(x["workflow"]["nextflow"]["version"])
    #     print(x["workflow-launch"]["revision"])

    # Get critical info, flatten and rename to user friendly values
    data_to_extract = {
        # "pipeline": "workflow-info.general.pipeline",
        # "workspace": "workflow-info.general.workspace",
        # "workflowUrl": "workflow-info.general.url",
        "name": "workflow-launch.computeEnv.name",
        "status": "workflow.status",
        "revision": "workflow-launch.revision",
        "service_version": "service-info.version",
        "nextflow_version": "workflow.nextflow.version",
    }
    parsed_data = [parse_json(x, data_to_extract) for x in extracted_data]

    la_mesa = tabulate(parsed_data, headers="keys", tablefmt="simple")

    # Convert into Slack Hook here.
    print(la_mesa)


if __name__ == "__main__":
    main()
