name: data-studios-heartbeat-production

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        type: string
        description: Space separated list of workspace IDs
        default: "138659136604200 40230138858677"
      slack:
        description: Whether to send a Slack message
        type: boolean
        required: false
        default: true
  schedule:
    - cron: "0 2 * * *" # Runs at 2 AM UTC every day

env:
  TOWER_API_ENDPOINT: "https://api.cloud.seqera.io"

jobs:
  check-data-studios:
    runs-on: ubuntu-latest
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: install tw cli
        run: |
          set -euo pipefail
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.10.1/tw-linux-x86_64
          mv tw-* tw
          chmod +x tw
          sudo mv tw /usr/local/bin/

      - name: tower check
        run: |
          tw --version

      - name: launch_pipelines
        run: |
          python studios_api_test.py \
            -w ${{ github.event_name == 'workflow_dispatch' && inputs.workspace_id || '138659136604200 40230138858677' }} \
            --slack_channel ${{ secrets.SLACK_CHANNEL }} \
            ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.slack) && '--slack' || '' }}
