name: heartbeat-checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Runs at 2 AM UTC every day

env:
  TOWER_API_ENDPOINT: ${{ secrets.STAGING_TOWER_ACCESS_ENDPOINT }}

jobs:
  launch-tower-workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        launch:
          - name: aws
            workspace_id: 64430228002560
            pipeline: heartbeat-nf-core-rnaseq-aws-test-full
          - name: azure
            workspace_id: 280116106690509
            pipeline: heartbeat-nf-core-rnaseq-azure-test-full
          - name: gcp
            workspace_id: 124007984423021
            pipeline: heartbeat-nf-core-rnaseq-google-test-full

    steps:
      - uses: seqeralabs/action-tower-launch@034c8f3bfa546bcc7b803540faa5e74af25e36a8
        with:
          access_token: ${{ secrets.STAGING_TOWER_ACCESS_TOKEN }}
          run_name: heartbeat-${{ matrix.launch.name }}_${{ github.run_id }}
          workspace_id: ${{ matrix.launch.workspace_id }}
          pipeline: ${{ matrix.launch.pipeline }}
          api_endpoint: ${{ secrets.STAGING_TOWER_ACCESS_ENDPOINT }}

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: tower_logs_run_${{ matrix.launch.name }}_${{ github.run_id }}
          path: |
            tower_action_*.log
            tower_action_*.json
