name: seqera-showcase-autotest
run-name: run-pipelines
on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: "Dryrun (do not submit pipeline)"
        default: false
        type: boolean
        required: false
      timer:
        description: "Environment"
        default: delay120mins
        type: choice
        options:
          - noDelay
          - delay1mins
          - delay5mins
          - delay15mins
          - delay30mins
          - delay60mins
          - delay120mins
          - delay360mins
          - waitForReviewer
      slack:
        description: Slack hook
        type: boolean
        required: false
        default: true
      remove:
        description: Delete run
        default: true
        type: boolean
        required: false

  schedule:
    # Every 2am
    - cron: "0 2 * * *"

jobs:
  launch:
    runs-on: ubuntu-latest
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: install tw cli
        run: |
          set -euo pipefail
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.9.1/tw-linux-x86_64
          mv tw-* tw
          chmod +x tw
          sudo mv tw /usr/local/bin/

      - name: tower check
        run: |
          tw --version

      - name: launch_pipelines
        run: |
          python launch_pipelines.py \
            -l DEBUG \
            -p hello.json nf-core-pipelines.json \
            -c aws.json azure.json gcp.json \
            -i include.json \
            -e exclude.json \
            -o ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}.json

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}_launch_json
          path: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}.json

  clearup-and-delete:
    runs-on: ubuntu-latest
    needs: [launch]
    environment: ${{ inputs.timer || 'delay60mins' }}
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}_launch_json
          path: run_details

      - name: Install tw CLI
        run: |
          set -euo pipefail
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.9.1/tw-linux-x86_64
          mv tw-* tw
          chmod +x tw
          sudo mv tw /usr/local/bin/

      - name: tower check
        run: |
          tw --version

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: finish workflow
        run: |
          python extract_metadata.py \
            -l DEBUG \
            -o ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}_workflow_data.json \
            -i run_details/* \
            --slack \
            --delete \
            --force

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}_workflow_data
          path: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}_workflow_data.json
